apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: docker.io/mirkolabs/service-b:0.0.6
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
