apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingresslabs
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-binding-examples 
# - kind: Group
#   name: system:authenticated
#   apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io/v1
