apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  labels:
    app: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: rng:0.0.1
        ports:
        - containerPort: 80

